name: Dummy Workflow

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  dummy_job:
    runs-on: ubuntu-latest

    steps:
    - name: Dummy step
      run: echo "This is a dummy workflow running."
